name: Add label through issue comment
on:
  issue_comment:
    types: [created, edited]

jobs:
  deployment:
    name: Create deployment
    runs-on: ubuntu-latest
    if: |
      github.event.comment.body == '/deploy test' ||
      github.event.comment.body == '/deploy staging' ||
      github.event.comment.body == '/deploy qa'

    steps:
      - name: Debug
        uses: actions/github-script@v2
        with:
          script: |
            console.log("\ncontext:\n\n");
            console.log(JSON.stringify(context, null, 2));
