name: Add label through issue comment
on:
  issue_comment:
    types: [created, edited]

jobs:
  deployment:
    name: Add label
    runs-on: ubuntu-latest
    if: |
      github.event.comment.body == '/deploy test' ||
      github.event.comment.body == '/deploy staging' ||
      github.event.comment.body == '/deploy qa'

    steps:
      - name: Output workflow context (for debugging)
        uses: actions/github-script@v3
        with:
          script: |
            console.log(JSON.stringify(context, null, 2));

      - name: Get temporary token for adding label
        id: temp_token
        uses: peter-murray/workflow-application-token-action@v1
        with:
          application_id: ${{ secrets.OCTODEMOBOT_APPLICATION_ID_REPO_AUTOMATION }}
          application_private_key: ${{ secrets.OCTODEMOBOT_APPLICATION_KEY_REPO_AUTOMATION }}

          apply-label:

      - name: Add label using temporary token
        uses: actions/github-script@v3
        with:
          github-token: ${{ steps.temp_token.outputs.token }}
          script: |
            const comment = context.payload.comment;
            const target = comment.body
                           .replace('/deploy ', '')
                           .replace('test', 'Test')
                           .replace('staging', 'Staging')
                           .replace('qa', 'QA');
            github.issues.addLabels({
              ...context.repository,
              labels: [`Deploy to ${target}`]
            });
