name: Add label through issue comment
on:
  issue_comment:
    types: [created, edited]

jobs:
  deployment:
    name: Create deployment
    runs-on: ubuntu-latest
    if: |
      github.event.issue.body == '/deploy test') ||
      github.event.issue.body == '/deploy staging') ||
      github.event.issue.body == '/deploy qa') ||

    steps:
      - name: Debug
        uses: actions/github-script@v2
        with:
          script: |
            console.log(JSON.stringify(context, null, 2));
