
name: Deployment Status Change

on:
  deployment_status:
  
jobs:
  report:
    runs-on: ubuntu-20.04
    
    steps:
      - name: Report event
        uses: actions/github-script@v2
        with:
          script: |
            console.log(JSON.stringify(context.payload, null, 2));
