name: Workflow - Enable

on:
  workflow_dispatch:
    inputs:
      workflow_file:
        default: deploy_environment__cloud_run.yml
        required: true
        description: The workflow file

jobs:
  enable_worflow:
    name: Enable Workflow

    runs-on: ubuntu-latest

    steps:
      - name: Enable workflow
        uses: actions/github-script@v3
        env:
          workflow_file: ${{ github.event.inputs.workflow_file }}
        with:
          script: |
            await github.request('PUT /repos/{owner}/{repo}/actions/workflows/{workflow_id}/enable', {
              ...context.repo
              workflow_id: process.env.workflow_file
            });