name: Workflow Run Trigger

on:
  workflow_run:
    workflows:
      - "Build and Deploy - Production"
    branches:
      - main
    types:
      - completed
      - requested
    

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Run
        run: echo "Hello we got triggered"
